---
- include: "bridge.yml"
- include: "dnsmasq.yml"
- include: "lxc.yml"

# FIXME: I don't know why but it seems we have to do that...
- name: stop lxc service
  service:
    name="lxc"
    state=stopped
  changed_when: False

- name: restart dnsmasq service
  service:
    name="dnsmasq"
    state=restarted
  changed_when: False
  
- name: start lxc service
  service:
    name="lxc"
    state=started
  changed_when: False
