---
- name: enable IP forward
  template:
    src="templates/etc_sysctl.d_99-enable-ip-forward.conf.j2"
    dest="/etc/sysctl.d/99-enable-ip-forward.conf"
  register: enable_ip_forward

- name: reload sysctl
  command: "sysctl -p"
  when: "{{ enable_ip_forward.changed }}"

- name: configure UFW forward policy
  lineinfile:
    dest="{{ item.file }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backrefs=yes
  with_items:
  - { file: "/etc/default/ufw",     regexp: "^#?DEFAULT_FORWARD_POLICY=.*",           line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\"" }
  - { file: "/etc/ufw/sysctl.conf", regexp: "^#?net/ipv4/ip_forward=.*",              line: "net/ipv4/ip_forward=1" }
  - { file: "/etc/ufw/sysctl.conf", regexp: "^#?net/ipv6/conf/default/forwarding=.*", line: "net/ipv6/conf/default/forwarding=1" }

#- name: configure NAT rules
#  lineinfile:
#    dest="/etc/ufw/before.rules"
#    line="{{ item.line }}"
#    insertbefore="^COMMIT"
#  with_items:
#  - { line: "*nat" }
#  - { line: ":POSTROUTING ACCEPT [0:0]" }
#  - { line: "-A POSTROUTING -s 192.168.0.0/24 -o eth0 -j MASQUERADE" }
