- name: enable IP forwarding
  template:
    src="templates/etc_sysctl.d_30-ipforward.conf.j2"
    dest="/etc/sysctl.d/30-ipforward.conf"
  register: configure_ip_forwarding

- name: reload sysctl
  command: "sysctl -p"
  when: "{{ configure_ip_forwarding.changed }}"

- name: install firewall
  yum:
    name="firewalld"
    state=installed

- name: start firewall
  service:
    name="firewalld"
    enabled=yes
    state=started

- name: configure public zone of firewall
  firewalld:
    interface="eth0"
    zone="public"
    permanent=true
    state=enabled
  register: interface_public_zone

- name: enable masquerade on public zone of firewall
  firewalld:
    masquerade=yes
    zone="public"
    permanent=true
    state=enabled
  register: masquerade_public_zone

- name: restart firewall
  service:
    name="firewalld"
    state=restarted
  when: "{{ interface_public_zone.changed or masquerade_public_zone.changed }}"
